name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    env:
      TEST_MONGO_URI: mongodb://localhost:27017/testdb
      JWT_SECRET: testsecret
      EMAIL_USER: test@example.com
      EMAIL_PASS: testpassword
      PORT: 5000
      NODE_ENV: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Debug Working Directory
        run: pwd

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
